config/routes.rb
Rails.application.routes.draw do
  resources :playlist_tracks
  resources :invoice_lines
  resources :tracks
  resources :invoices
  resources :albums
  resources :customers
  resources :artists
  devise_for :users
  resources :media_types
  resources :playlists
  resources :genres
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/media_types_controller.rb
class MediaTypesController < ApplicationController
  before_action :set_media_type, only: [:show, :edit, :update, :destroy]

  # GET /media_types
  # GET /media_types.json
  def index
    @media_types = MediaType.all
  end

  # GET /media_types/1
  # GET /media_types/1.json
  def show
  end

  # GET /media_types/new
  def new
    @media_type = MediaType.new
  end

  # GET /media_types/1/edit
  def edit
  end

  # POST /media_types
  # POST /media_types.json
  def create
    @media_type = MediaType.new(media_type_params)

    respond_to do |format|
      if @media_type.save
        format.html { redirect_to @media_type, notice: 'Media type was successfully created.' }
        format.json { render :show, status: :created, location: @media_type }
      else
        format.html { render :new }
        format.json { render json: @media_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /media_types/1
  # PATCH/PUT /media_types/1.json
  def update
    respond_to do |format|
      if @media_type.update(media_type_params)
        format.html { redirect_to @media_type, notice: 'Media type was successfully updated.' }
        format.json { render :show, status: :ok, location: @media_type }
      else
        format.html { render :edit }
        format.json { render json: @media_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /media_types/1
  # DELETE /media_types/1.json
  def destroy
    @media_type.destroy
    respond_to do |format|
      format.html { redirect_to media_types_url, notice: 'Media type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_media_type
      @media_type = MediaType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def media_type_params
      params.require(:media_type).permit(:name)
    end
end

app/views/media_types/_form.html.erb
<%= simple_form_for(@media_type) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/media_types/edit.html.erb
<h1>Editing Media Type</h1>

<%= render 'form', media_type: @media_type %>

<%= link_to 'Show', @media_type %> |
<%= link_to 'Back', media_types_path %>

app/views/media_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Media Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @media_types.each do |media_type| %>
      <tr>
        <td><%= media_type.name %></td>
        <td><%= link_to 'Show', media_type %></td>
        <td><%= link_to 'Edit', edit_media_type_path(media_type) %></td>
        <td><%= link_to 'Destroy', media_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Media Type', new_media_type_path %>

app/views/media_types/new.html.erb
<h1>New Media Type</h1>

<%= render 'form', media_type: @media_type %>

<%= link_to 'Back', media_types_path %>

app/views/media_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @media_type.name %>
</p>

<%= link_to 'Edit', edit_media_type_path(@media_type) %> |
<%= link_to 'Back', media_types_path %>