config/routes.rb
Rails.application.routes.draw do
  resources :playlist_tracks
  resources :invoice_lines
  resources :tracks
  resources :invoices
  resources :albums
  resources :customers
  resources :artists
  devise_for :users
  resources :media_types
  resources :playlists
  resources :genres
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice_line.rb
class InvoiceLine < ApplicationRecord
  belongs_to :track
  belongs_to :invoice
end

app/controllers/invoice_lines_controller.rb
class InvoiceLinesController < ApplicationController
  before_action :set_invoice_line, only: [:show, :edit, :update, :destroy]

  # GET /invoice_lines
  # GET /invoice_lines.json
  def index
    @invoice_lines = InvoiceLine.all
  end

  # GET /invoice_lines/1
  # GET /invoice_lines/1.json
  def show
  end

  # GET /invoice_lines/new
  def new
    @invoice_line = InvoiceLine.new
  end

  # GET /invoice_lines/1/edit
  def edit
  end

  # POST /invoice_lines
  # POST /invoice_lines.json
  def create
    @invoice_line = InvoiceLine.new(invoice_line_params)

    respond_to do |format|
      if @invoice_line.save
        format.html { redirect_to @invoice_line, notice: 'Invoice line was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_line }
      else
        format.html { render :new }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_lines/1
  # PATCH/PUT /invoice_lines/1.json
  def update
    respond_to do |format|
      if @invoice_line.update(invoice_line_params)
        format.html { redirect_to @invoice_line, notice: 'Invoice line was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_line }
      else
        format.html { render :edit }
        format.json { render json: @invoice_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_lines/1
  # DELETE /invoice_lines/1.json
  def destroy
    @invoice_line.destroy
    respond_to do |format|
      format.html { redirect_to invoice_lines_url, notice: 'Invoice line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_line
      @invoice_line = InvoiceLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_line_params
      params.require(:invoice_line).permit(:track_id, :invoice_id, :unit_price)
    end
end

app/views/invoice_lines/_form.html.erb
<%= simple_form_for(@invoice_line) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :track %>
    <%= f.association :invoice %>
    <%= f.input :unit_price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/invoice_lines/edit.html.erb
<h1>Editing Invoice Line</h1>

<%= render 'form', invoice_line: @invoice_line %>

<%= link_to 'Show', @invoice_line %> |
<%= link_to 'Back', invoice_lines_path %>

app/views/invoice_lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoice Lines</h1>

<table>
  <thead>
    <tr>
      <th>Track</th>
      <th>Invoice</th>
      <th>Unit price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_lines.each do |invoice_line| %>
      <tr>
        <td><%= invoice_line.track %></td>
        <td><%= invoice_line.invoice %></td>
        <td><%= invoice_line.unit_price %></td>
        <td><%= link_to 'Show', invoice_line %></td>
        <td><%= link_to 'Edit', edit_invoice_line_path(invoice_line) %></td>
        <td><%= link_to 'Destroy', invoice_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice Line', new_invoice_line_path %>

app/views/invoice_lines/new.html.erb
<h1>New Invoice Line</h1>

<%= render 'form', invoice_line: @invoice_line %>

<%= link_to 'Back', invoice_lines_path %>

app/views/invoice_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Track:</strong>
  <%= @invoice_line.track %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @invoice_line.invoice %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @invoice_line.unit_price %>
</p>

<%= link_to 'Edit', edit_invoice_line_path(@invoice_line) %> |
<%= link_to 'Back', invoice_lines_path %>